const prefix='CUSTOMER'

export const Types = {    
    LOAD_CUSTOMERS: `${prefix}/LOAD_CUSTOMERS`,
    LOAD_CUSTOMERS_SUCCESS: `${prefix}/LOAD_CUSTOMERS_SUCCESS`,
    DELETE_CUSTOMER: `${prefix}/DELETE_CUSTOMER`,
    DELETE_CUSTOMERS_SUCCESS: `${prefix}/DELETE_CUSTOMER_SUCCESS`,
    FILTER_CUSTOMERS: `${prefix}/FILTER_CUSTOMERS`,
};